In [2]:
import numpy as np
import pandas as pd
import AJ_DecisionTree as dt
from leaf import leaf

In [3]:
data = pd.read_csv('/home/msc2/Documents/Academics 3rd Sem/MDSC-301/data/Mall_Customers_train.csv')

data.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0         138    Male   32                  73                      73
1         181  Female   37                  97                      32
2         131    Male   47                  71                       9
3           5  Female   31                  17                      40
4         200    Male   30                 137                      83

In [4]:
in_data = data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]
out_data = data[['Gender']]

in_data.head()

Age  Annual Income (k$)  Spending Score (1-100)
0   32                  73                      73
1   37                  97                      32
2   47                  71                       9
3   31                  17                      40
4   30                 137                      83

In [5]:
in_cols = list(in_data.columns)

in_cols

['Age', 'Annual Income (k$)', 'Spending Score (1-100)']

In [6]:
data_male = data[data['Gender'] == 'Male']
data_female = data[data['Gender'] == 'Female']

p_male = data_male.shape[0]/data.shape[0]
p_female = data_female.shape[0]/data.shape[0]

E = 1 - p_male**2 - p_female**2

E

0.4921875

In [7]:
Age_values = np.sort(data['Age'].unique())
Income_values = np.sort(data['Annual Income (k$)'].unique())
Spending_values = np.sort(data['Spending Score (1-100)'].unique())

Age_values

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 57, 58, 59, 60, 63, 64, 65, 66, 67, 68, 69, 70])

In [8]:
partitions = {}

partitions[in_cols[0]] = dt.axis_partitions(Age_values)
partitions[in_cols[1]] = dt.axis_partitions(Income_values)
partitions[in_cols[2]] = dt.axis_partitions(Spending_values)

partitions[in_cols[0]]

array([18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5,
       29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5,
       40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5,
       51.5, 52.5, 53.5, 54.5, 56. , 57.5, 58.5, 59.5, 61.5, 63.5, 64.5,
       65.5, 66.5, 67.5, 68.5, 69.5])

In [9]:
data_filt1 = data[data['Age'] < partitions[in_cols[0]][0]]
data_filt2 = data[data['Age'] > partitions[in_cols[0]][0]]

data_filt1_male = data_filt1[data_filt1['Gender'] == 'Male']
data_filt1_female = data_filt1[data_filt1['Gender'] == 'Female']

data_filt2_male = data_filt2[data_filt2['Gender'] == 'Male']
data_filt2_female = data_filt2[data_filt2['Gender'] == 'Female']

p1 = data_filt1.shape[0]/data.shape[0]
p2 = data_filt2.shape[0]/data.shape[0]

p1_male = data_filt1_male.shape[0]/data_filt1.shape[0]
p1_female = data_filt1_female.shape[0]/data_filt1.shape[0]

p2_male = data_filt2_male.shape[0]/data_filt2.shape[0]
p2_female = data_filt2_female.shape[0]/data_filt2.shape[0]

E1 = 1 - p1_male**2 - p1_female**2
E2 = 1 - p2_male**2 - p2_female**2

dE = E - p1*E1 - p2*E2

dE

0.002007032908704909

In [10]:
dE = {}

dE[in_cols[0]] = np.zeros((partitions[in_cols[0]].shape[0],))
for i in range(partitions[in_cols[0]].shape[0]):
    data_filt1 = data[data['Age'] < partitions[in_cols[0]][i]]
    data_filt2 = data[data['Age'] > partitions[in_cols[0]][i]]

    data_filt1_male = data_filt1[data_filt1['Gender'] == 'Male']
    data_filt1_female = data_filt1[data_filt1['Gender'] == 'Female']

    data_filt2_male = data_filt2[data_filt2['Gender'] == 'Male']
    data_filt2_female = data_filt2[data_filt2['Gender'] == 'Female']

    p1 = data_filt1.shape[0]/data.shape[0]
    p2 = data_filt2.shape[0]/data.shape[0]

    p1_male = data_filt1_male.shape[0]/data_filt1.shape[0]
    p1_female = data_filt1_female.shape[0]/data_filt1.shape[0]

    p2_male = data_filt2_male.shape[0]/data_filt2.shape[0]
    p2_female = data_filt2_female.shape[0]/data_filt2.shape[0]

    E1 = 1 - p1_male**2 - p1_female**2
    E2 = 1 - p2_male**2 - p2_female**2

    dE[in_cols[0]][i] = E - p1*E1 - p2*E2

print('Age dE = ', dE[in_cols[0]], '\n\nMax = ', np.max(dE[in_cols[0]]), '\n\nAge Partition point = ',
      partitions[in_cols[0]][np.argmax(dE[in_cols[0]])])

Age dE =  [2.00703291e-03 1.75208333e-02 2.32540362e-02 1.71257970e-02
 1.01512925e-02 2.38267613e-03 2.66508285e-03 1.65719697e-03
 2.81529679e-03 1.30178571e-03 2.43340164e-03 1.06562752e-03
 3.72023810e-04 9.22650245e-04 7.99020209e-04 6.19939271e-05
 1.11980411e-05 8.91145752e-04 2.58462320e-03 1.50122549e-03
 1.79067460e-03 1.51711202e-04 5.14318631e-06 1.87500000e-04
 1.17993791e-05 1.33069324e-06 3.04383117e-04 1.15858094e-03
 1.02452105e-03 1.34081808e-03 1.39758497e-05 1.44370743e-03
 3.13357492e-03 5.90968055e-03 5.77660240e-03 4.09226190e-03
 7.50612745e-03 9.84062599e-03 9.95899709e-03 1.01512925e-02
 5.40222645e-03 8.08769569e-03 8.51632883e-03 5.83911684e-03
 6.26034768e-03 3.70065789e-03 1.70362903e-03 8.01028481e-03
 3.97995283e-03] 

Max =  0.023254036203522566 

Age Partition point =  20.5


In [11]:
dE[in_cols[1]] = np.zeros((partitions[in_cols[1]].shape[0],))
for i in range(partitions[in_cols[1]].shape[0]):
    data_filt1 = data[data['Annual Income (k$)'] < partitions[in_cols[1]][i]]
    data_filt2 = data[data['Annual Income (k$)'] > partitions[in_cols[1]][i]]

    data_filt1_male = data_filt1[data_filt1['Gender'] == 'Male']
    data_filt1_female = data_filt1[data_filt1['Gender'] == 'Female']

    data_filt2_male = data_filt2[data_filt2['Gender'] == 'Male']
    data_filt2_female = data_filt2[data_filt2['Gender'] == 'Female']

    p1 = data_filt1.shape[0]/data.shape[0]
    p2 = data_filt2.shape[0]/data.shape[0]

    p1_male = data_filt1_male.shape[0]/data_filt1.shape[0]
    p1_female = data_filt1_female.shape[0]/data_filt1.shape[0]

    p2_male = data_filt2_male.shape[0]/data_filt2.shape[0]
    p2_female = data_filt2_female.shape[0]/data_filt2.shape[0]

    E1 = 1 - p1_male**2 - p1_female**2
    E2 = 1 - p2_male**2 - p2_female**2

    dE[in_cols[1]][i] = E - p1*E1 - p2*E2

print('Income dE = ', dE[in_cols[1]], '\n\nMax = ', np.max(dE[in_cols[1]]), '\n\nIncome Partition point = ',
      partitions[in_cols[1]][np.argmax(dE[in_cols[1]])])

Income dE =  [8.01028481e-03 2.00703291e-03 9.07258065e-05 2.10813492e-03
 2.52083333e-03 2.98027865e-03 2.24497126e-03 1.70004628e-03
 2.75088028e-03 1.73954216e-03 3.82965686e-03 3.23801665e-03
 2.73944805e-03 5.00801282e-03 4.39453125e-03 6.30040323e-03
 1.08620073e-02 9.99340285e-03 1.08003527e-02 1.00174008e-02
 5.46022727e-03 8.03507835e-03 5.28152146e-03 6.47079953e-03
 9.18750000e-03 1.92434211e-03 3.52195675e-03 4.49568414e-03
 5.58533405e-03 6.01528127e-03 4.56004902e-03 3.69320402e-03
 8.29863294e-04 7.10227273e-04 2.51955925e-03 4.11057692e-03
 3.86725781e-03 4.94260204e-03 8.92706220e-04 2.14629121e-03
 1.80288462e-03 1.64204545e-03 1.48809524e-03 3.15241228e-03
 2.96336207e-03 2.10813492e-03 3.13357492e-03 2.97144599e-03
 2.81529679e-03 1.65719697e-03 2.47937163e-06 7.29050019e-05
 1.70004628e-03 2.90948276e-04 1.23838063e-03 1.75957207e-03
 2.52083333e-03 7.29458450e-06 9.07258065e-05 2.00703291e-03
 3.97995283e-03] 

Max =  0.010862007310871002 

Income Partition point 

In [12]:
dE[in_cols[2]] = np.zeros((partitions[in_cols[2]].shape[0],))
for i in range(partitions[in_cols[2]].shape[0]):
    data_filt1 = data[data['Spending Score (1-100)'] < partitions[in_cols[2]][i]]
    data_filt2 = data[data['Spending Score (1-100)'] > partitions[in_cols[2]][i]]

    data_filt1_male = data_filt1[data_filt1['Gender'] == 'Male']
    data_filt1_female = data_filt1[data_filt1['Gender'] == 'Female']

    data_filt2_male = data_filt2[data_filt2['Gender'] == 'Male']
    data_filt2_female = data_filt2[data_filt2['Gender'] == 'Female']

    p1 = data_filt1.shape[0]/data.shape[0]
    p2 = data_filt2.shape[0]/data.shape[0]

    p1_male = data_filt1_male.shape[0]/data_filt1.shape[0]
    p1_female = data_filt1_female.shape[0]/data_filt1.shape[0]

    p2_male = data_filt2_male.shape[0]/data_filt2.shape[0]
    p2_female = data_filt2_female.shape[0]/data_filt2.shape[0]

    E1 = 1 - p1_male**2 - p1_female**2
    E2 = 1 - p2_male**2 - p2_female**2

    dE[in_cols[2]][i] = E - p1*E1 - p2*E2

print('Spending dE = ', dE[in_cols[2]], '\n\nMax = ', np.max(dE[in_cols[2]]), '\n\nSpending Partition point = ',
      partitions[in_cols[2]][np.argmax(dE[in_cols[2]])])

Spending dE =  [8.01028481e-03 1.20919586e-02 1.62259615e-02 1.02796053e-02
 6.26034768e-03 3.52083333e-03 5.83911684e-03 8.51632883e-03
 1.46923924e-02 1.71257970e-02 1.29017857e-02 1.54737583e-02
 1.24080882e-02 1.22793485e-02 1.22091450e-02 9.79081666e-03
 7.70032051e-03 7.81250000e-03 6.05650501e-03 3.30178571e-03
 4.73230287e-03 3.47622775e-03 1.59097531e-03 9.37500000e-04
 1.57637207e-04 1.20003918e-03 1.34081808e-03 1.16347215e-04
 5.56445869e-04 2.99405979e-04 5.20833333e-04 9.43088674e-04
 1.02479757e-04 1.99808184e-05 1.23012124e-06 1.76221805e-04
 9.88924051e-05 4.88586617e-06 4.41939032e-05 7.89141414e-05
 5.03707286e-06 4.16598091e-04 1.56534608e-04 1.17993791e-05
 1.36486723e-04 2.00320513e-04 2.78409091e-04 7.59847858e-04
 3.72023810e-04 9.19377236e-04 1.72220633e-03 1.98373824e-03
 1.30596551e-03 3.60281308e-04 1.68518119e-04 2.52016129e-04
 1.22100838e-03 6.49038462e-04 1.95802005e-05 2.24239380e-04
 6.68981481e-04 1.53186275e-04 2.47937163e-06 2.40878726e-05
 4.464285

In [13]:
possible_partitions = {}

for i in range(len(in_cols)):
    part_idx = np.argmax(dE[in_cols[i]])
    possible_partitions[(in_cols[i], partitions[in_cols[i]][part_idx])] = (dE[in_cols[i]][part_idx], part_idx)

possible_partitions

{('Age', 20.5): (0.023254036203522566, 2),
 ('Annual Income (k$)', 41.0): (0.010862007310871002, 16),
 ('Spending Score (1-100)', 13.5): (0.017125796997120468, 9)}

In [14]:
max_feat = dt.get_max_feat(possible_partitions)

max_feat

{'max_feat': ('Age', 20.5), 'part_idx': 2}

In [15]:
data_parts = dt.data_split(data, max_feat['max_feat'][0], max_feat['max_feat'][1])

target= 0

index= data.columns
for i in range(len(index)):
    if index[i]== 'Gender':
        target= i

data_part1_male= []
data_part1_female= []
data_part2_male= []
data_part2_female= []

for i in range(len(data_parts[0])):
    if(data_parts[0][i][target]== 'Male'):
        data_part1_male.append(data_parts[0][i])
    else:
        data_part1_female.append(data_parts[0][i])
        
for i in range(len(data_parts[1])):
    if(data_parts[1][i][target]== 'Male'):
        data_part2_male.append(data_parts[1][i])
    else:
        data_part2_female.append(data_parts[1][i])

p1 = len(data_parts[0])/data.shape[0]
p2 = len(data_parts[1])/data.shape[0]

p1_male = len(data_part1_male)/len(data_parts[0])
p1_female = len(data_part1_female)/len(data_parts[0])

p2_male = len(data_part2_male)/len(data_parts[1])
p2_female = len(data_part2_female)/len(data_parts[1])

print('if Age below', max_feat['max_feat'][1], ': Male =', p1_male*100, '%, Female =', p1_female*100, '%')
print('if Age above', max_feat['max_feat'][1], ': Male =', p2_male*100, '%, Female =', p2_female*100, '%')

if Age below 20.5 : Male = 78.57142857142857 %, Female = 21.428571428571427 %
if Age above 20.5 : Male = 40.41095890410959 %, Female = 59.589041095890416 %


In [16]:
categories = list(data['Gender'].unique())

classes = {}
for i in range(len(categories)):
    classes[categories[i]] = leaf(categories[i])

classes

{'Male': <leaf.leaf at 0x7f95ae5c69e8>,
 'Female': <leaf.leaf at 0x7f95ae46f0b8>}

In [17]:
tree_predict = {}

pL = np.array([p1_male, p1_female])
pR = np.array([p2_male, p2_female])
dt.add_stump(tree_predict, max_feat['max_feat'], pL, pR, categories)

tree_predict

{('Age', 20.5): {'T': ('pclass', 'Male'), 'F': ('pclass', 'Female')}}

In [18]:
tree = dt.to_plot_tree(tree_predict, classes)

tree

{'Age < 20.5': {'T': <leaf.leaf at 0x7f95ae5c69e8>,
  'F': <leaf.leaf at 0x7f95ae46f0b8>}}

In [19]:
dt.plot(tree, 'Mall_Customer_Tree')

In [20]:
pd.DataFrame(data_parts[0])

0       1   2   3   4
0   112  Female  19  63  54
1   139    Male  19  74  10
2   115  Female  18  65  48
3    18    Male  20  21  66
4    69    Male  19  48  59
5    40  Female  20  37  75
6    34    Male  18  33  92
7   114    Male  19  64  46
8     1    Male  19  15  39
9   135    Male  20  73   5
10   62    Male  19  46  55
11   66    Male  18  48  59
12  100    Male  20  61  49
13  163    Male  19  81   5

In [21]:
data_0_male= data_part1_male
data_0_female= data_part1_female
#for i in range(len(data_parts[0])):
#    if(data_parts[0][i][target]== 'Male'):
#        data_0_male.append(data_parts[0][i])
#    else:
#        data_1_female.append(data_parts[0][i])
#
#data_0_male = data_parts[0][data_parts[0]['Gender'] == 'Male']
#data_0_female = data_parts[0][data_parts[0]['Gender'] == 'Female']

p_male = len(data_0_male)/len(data_parts[0])
p_female = len(data_0_female)/len(data_parts[0])

E = 1 - p_male**2 - p_female**2

E

0.33673469387755106

In [22]:
data_part0= pd.DataFrame(data_parts[0])
index= data.columns
for i in range(len(index)):
    if index[i]== 'Age':
        column= i
Age_values = np.sort(data_part0[column].unique())
for i in range(len(index)):
    if index[i]== 'Annual Income (k$)':
        column= i
Income_values = np.sort(data_part0[column].unique())
for i in range(len(index)):
    if index[i]== 'Spending Score (1-100)':
        column= i
Spending_values = np.sort(data_part0[column].unique())

Spending_values

array([ 5, 10, 39, 46, 48, 49, 54, 55, 59, 66, 75, 92])

In [23]:
partitions = {}

partitions[in_cols[0]] = dt.axis_partitions(Age_values)
partitions[in_cols[1]] = dt.axis_partitions(Income_values)
partitions[in_cols[2]] = dt.axis_partitions(Spending_values)

partitions[in_cols[0]]

array([18.5, 19.5])